services:
  db:
    container_name: rust-api-db
    image: postgres:17.0
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rust-api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
